import React from "react";
import { SmartBadge } from "./SmartBadge";
import { normalizeSmartBadgeConfig } from "../smartBadgeConfig";
import { collectSmartBadgeRenderMetrics, createSmartBadgeExportJob, makeSmartBadgePdf, SMART_BADGE_EXPORT_GEOMETRY } from "../utils/smartBadgePdf";
import { createBadgeExportProfiler } from "../utils/badgeExportProfiler";
import "../smartBadge.css";
import "../smartBadgeControls.css";
import "../smartBadgeThemes.css";
import "../smartBadgeCompositions.css";

const program={id:"qa-program",name:"عمرة رمضان",departure:"2027-02-20"};
const makePhoto=(background,foreground,shape)=>"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 300"><rect width="240" height="300" fill="${background}"/><circle cx="120" cy="104" r="51" fill="${foreground}" opacity=".9"/>${shape}</svg>`);
const makeRasterPhoto=(width,height)=>{const canvas=document.createElement("canvas"),context=canvas.getContext("2d");canvas.width=width;canvas.height=height;const gradient=context.createLinearGradient(0,0,width,height);gradient.addColorStop(0,"#d9e4df");gradient.addColorStop(1,"#8ea49a");context.fillStyle=gradient;context.fillRect(0,0,width,height);for(let index=0;index<180;index+=1){context.fillStyle=`hsla(${(index*37)%360},35%,${35+(index%25)}%,.16)`;context.fillRect((index*173)%width,(index*251)%height,Math.max(8,width/19),Math.max(8,height/23));}context.fillStyle="#f8f5ec";context.beginPath();context.arc(width*.5,height*.35,width*.19,0,Math.PI*2);context.fill();context.beginPath();context.ellipse(width*.5,height*.79,width*.34,height*.29,0,0,Math.PI*2);context.fill();return canvas.toDataURL("image/jpeg",.98);};
const qaCases={
  short:{client:{id:"qa-short",name:"علي حسن",passport:{number:"UM6600198"},hotelMecca:"سنود أجياد",hotelMadina:"طيبة المدينة",badgePhotoPath:""},photo:makePhoto("#e7dfcf","#fff",'<path d="M36 276c7-70 43-105 84-105s77 35 84 105" fill="#fff" opacity=".88"/>')},
  long:{client:{id:"qa-long",name:"عبدالرحمن محمد عبدالسلام العثماني",passport:{number:"SG5080731"},hotelMecca:"جبل عمر حياة ريجنسي مكة",hotelMadina:"دار الإيمان إنتركونتيننتال",badgePhotoPath:""},photo:makePhoto("#d9e4df","#f8f5ec",'<path d="M28 284c12-76 48-110 92-110s80 34 92 110" fill="#f8f5ec" opacity=".92"/>')},
  photo:{client:{id:"qa-photo",name:"مريم عبدالله",passport:{number:"MA2048317"},hotelMecca:"فندق الصفوة رويال أوركيد",hotelMadina:"أنوار المدينة موڤنبيك",badgePhotoPath:""},photo:makePhoto("#d9d5e5","#fff",'<path d="M44 282c5-66 38-104 76-104s71 38 76 104" fill="#fff" opacity=".86"/>')},
};
const qaParams=new URLSearchParams(window.location.search),qaCaseName=qaParams.get("case"),selectedCase=qaCases[qaCaseName]||qaCases.short;
const agency={nameAr:"وكالة الأسفار الدولية"};
const {client,photo}=selectedCase;
const exportPhoto=qaCaseName==="large-photo"?makeRasterPhoto(3000,4000):qaCaseName==="print-photo"?makeRasterPhoto(685,913):photo;
const data={name:client.name,passport:client.passport.number,program:"عمرة رمضان",travelDate:"2027-02-20",makkahHotel:client.hotelMecca,madinahHotel:client.hotelMadina,phone:"+212 6 12 34 56 78",group:"المجموعة الثانية",room:"1203"};
const qaBackground=new URLSearchParams(window.location.search).get("background")||"";
const config=normalizeSmartBadgeConfig({printSource:"smart",content:{phone:true},appearance:{layoutFamily:"rukn-signature",...(qaBackground?{backgroundColorOverride:qaBackground}:{})}});
const requestedBenchmark=Number(new URLSearchParams(window.location.search).get("benchmark")||1);
const benchmarkCount=[1,10,25,50,212].includes(requestedBenchmark)?requestedBenchmark:1;

export function SmartBadgeExportQa(){
  const [raster,setRaster]=React.useState(""),[pdfPreview,setPdfPreview]=React.useState(""),[previewMetrics,setPreviewMetrics]=React.useState(null),[exportMetrics,setExportMetrics]=React.useState(null),[benchmarkSummary,setBenchmarkSummary]=React.useState(null),jpegRef=React.useRef(null),previewRef=React.useRef(null),runRef=React.useRef(0);
  React.useEffect(()=>{let url="",pdfUrl="",job=null;const runId=++runRef.current,isCurrent=()=>runRef.current===runId;requestAnimationFrame(()=>{const node=previewRef.current?.querySelector(".smart-badge");if(node&&isCurrent())setPreviewMetrics(collectSmartBadgeRenderMetrics(node));});const timer=setTimeout(()=>{(async()=>{const profiler=createBadgeExportProfiler({mode:"smart",badges:benchmarkCount,label:`QA ${benchmarkCount}`}),jpegs=[];job=createSmartBadgeExportJob({config,program,agency,profiler});try{await job.prepare(Array.from({length:benchmarkCount},()=>client));for(let index=0;index<benchmarkCount;index+=1){jpegs.push(await job.render({client,data,photoUrl:exportPhoto,onMetrics:index===0&&isCurrent()?setExportMetrics:undefined,badgeIndex:index+1,badgeTotal:benchmarkCount}));document.documentElement.dataset.benchmarkProgress=String(index+1);if(!isCurrent())return;}job.dispose();const blob=jpegs[0];jpegRef.current=blob;url=URL.createObjectURL(blob);setRaster(url);const pdf=await makeSmartBadgePdf(jpegs,profiler),summary=profiler.finish({pdfBlob:pdf});if(!isCurrent())return;setBenchmarkSummary(summary);pdfUrl=URL.createObjectURL(pdf);setPdfPreview(pdfUrl);document.documentElement.dataset.benchmarkComplete=String(benchmarkCount);if(new URLSearchParams(window.location.search).get("download")==="1"){const link=document.createElement("a");link.href=pdfUrl;link.download="smart-badge-export-qa.pdf";link.click();}}finally{job?.dispose();}})();},0);return()=>{clearTimeout(timer);if(runRef.current===runId)runRef.current+=1;job?.dispose();if(url)URL.revokeObjectURL(url);if(pdfUrl)URL.revokeObjectURL(pdfUrl);};},[]);
  React.useEffect(()=>{if(!previewMetrics||!exportMetrics)return;const ids=["passport","program","travelDate","makkahHotel","madinahHotel","phone","group","room"],anchors=ids.map((id)=>Math.round((previewMetrics[id]?.valueAnchor||0)*100)/100),exportAnchors=ids.map((id)=>Math.round((exportMetrics[id]?.valueAnchor||0)*100)/100);document.title=`SMART_BADGE_QA ${previewMetrics.badge.background} ${anchors.join(",")} | ${exportMetrics.badge.background} ${exportAnchors.join(",")}`;},[previewMetrics,exportMetrics]);
  const downloadPdf=async()=>{if(!jpegRef.current)return;const pdf=await makeSmartBadgePdf([jpegRef.current]),url=URL.createObjectURL(pdf),link=document.createElement("a");link.href=url;link.download="smart-badge-export-qa.pdf";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const size={width:`${SMART_BADGE_EXPORT_GEOMETRY.layoutWidthPx}px`,height:`${SMART_BADGE_EXPORT_GEOMETRY.layoutHeightPx}px`};
  const badge=<SmartBadge editor config={config} data={data} agency={agency} photoUrl={exportPhoto}/>;
  return <main className="smart-badge-export-qa" dir="rtl"><header><h1>Smart Badge Export QA</h1><p>نفس config ونفس أبعاد layout المنطقية قبل رفع الدقة إلى 300 DPI.</p><button type="button" disabled={!raster} onClick={downloadPdf}>Download QA PDF</button></header><pre id="smart-badge-qa-metrics">{JSON.stringify({preview:previewMetrics,export:exportMetrics})}</pre><pre id="smart-badge-benchmark-summary">{benchmarkSummary?JSON.stringify(benchmarkSummary):"pending"}</pre><div className="smart-badge-export-qa-grid"><figure><div ref={previewRef} className="smart-badge-identity smart-badge-export-host is-inline" style={size}>{badge}</div><figcaption>Preview</figcaption></figure><figure><div className="smart-badge-identity smart-badge-export-host is-inline" style={size}>{badge}</div><figcaption>Exact Export DOM</figcaption></figure>{raster&&<figure><img src={raster} alt="300 DPI raster destined for PDF"/><figcaption>300 DPI Raster</figcaption></figure>}{pdfPreview&&<figure><object className="smart-badge-export-pdf" data={`${pdfPreview}#toolbar=0&navpanes=0&scrollbar=0`} type="application/pdf" aria-label="Final PDF page"/><figcaption>Final 58×88mm PDF</figcaption></figure>}</div></main>;
}
