import React from "react";
import { useLang } from "../../hooks/useLang";

// Feature namespace layered on RUKN's existing LangProvider. The Arabic source
// is kept as the stable lookup key so existing config IDs and enums never move.
const rows = [
  ["مصدر تصميم الشارة","Source du design du badge","Badge design source"],["يحدد التصميم المستخدم عند التنزيل والطباعة فقط","Détermine le design utilisé uniquement au téléchargement et à l’impression","Determines the design used only for download and printing"],["هوية الشارة","Identité du badge","Badge Identity"],["قالب الشارة","Modèle du badge","Badge template"],["استعمال تصميم Smart Badge المحفوظ","Utiliser le design Smart Badge enregistré","Use the saved Smart Badge design"],["استعمال القالب المرتبط بالبرنامج","Utiliser le modèle associé au programme","Use the template linked to the program"],["تعذر حفظ مصدر تصميم الشارة","Impossible d’enregistrer la source du badge","Unable to save badge design source"],["تم حفظ مصدر تصميم الشارة","Source du badge enregistrée","Badge design source saved"],
  ["الشارات","Badges","Badges"],["هوية ذكية جاهزة أو مصمم الشارات الحالي.","Identité intelligente ou concepteur de badges classique.","Smart identity or the current badge designer."],["مسارات الشارات","Espaces des badges","Badge workspaces"],["تصميم ذكي يتكيف تلقائيا","Design intelligent à adaptation automatique","Smart design that adapts automatically"],["قوالب الشارات","Modèles de badges","Badge templates"],["ارفع تصميم الشارة، ضع الحقول، ثم استعمله لطباعة شارات المعتمرين.","Importez le design, placez les champs puis imprimez les badges des pèlerins.","Upload the design, place fields, then print pilgrim badges."],
  ["بيانات المعاينة","Données d’aperçu","Preview data"],["بيانات معاينة","Données d’aperçu","Preview data"],["بيانات فعلية","Données réelles","Real data"],["البرنامج","Programme","Program"],["كل البرامج","Tous les programmes","All programs"],["برنامج","Programme","Program"],["ابحث عن معتمر","Rechercher un pèlerin","Search for a pilgrim"],["الاسم أو رقم الجواز","Nom ou numéro de passeport","Name or passport number"],["معتمر","Pèlerin","Pilgrim"],["لا توجد نتائج مطابقة","Aucun résultat correspondant","No matching results"],
  ["نظام التصميم","Système de design","Design system"],["التصميم","Design","Design"],["القوالب الأصلية","Modèles d’origine","Original templates"],["تخصيص مكونات التصميم","Personnaliser les composants","Customize design components"],["مظهر المكونات","Apparence des composants","Component appearance"],["الخلفية","Arrière-plan","Background"],["حاوية الاسم والصورة","Conteneur du nom et de la photo","Name and photo container"],["نصوص الحقول","Textes des champs","Field typography"],["شكل الحقول","Style des champs","Field style"],["المحتوى","Contenu","Content"],["العلامة المائية","Filigrane","Watermark"],["الهوية","Identité","Identity"],["الكثافة","Densité","Density"],
  ["الهوية العلوية","Identité supérieure","Header identity"],["الاسم والصورة","Nom et photo","Name and photo"],["البيانات الأساسية","Données principales","Primary data"],["البيانات الثانوية","Données secondaires","Secondary data"],["الفواصل والتفاصيل","Séparateurs et détails","Separators and details"],["التذييل","Pied de page","Footer"],["إطار الصورة","Cadre de la photo","Photo frame"],
  ["الوجه","Recto","Front"],["الظهر","Verso","Back"],["جهة الشارة","Côté du badge","Badge side"],["عرض الوجه الأمامي","Afficher le recto","Show front side"],["عرض ظهر الشارة","Afficher le verso","Show back side"],["معاينة","Aperçu","Preview"],["معاينة الشارة","Aperçu du badge","Badge preview"],["معاينة الشارة كاملة","Aperçu complet du badge","Full badge preview"],["إغلاق معاينة الشارة","Fermer l’aperçu du badge","Close badge preview"],["مفعّل","Activé","Enabled"],["غير مفعّل","Désactivé","Disabled"],["قابل للتخصيص","Personnalisable","Customizable"],
  ["تفعيل ظهر الشارة","Activer le verso du badge","Enable badge back"],["لون خلفية ظهر الشارة","Couleur de fond du verso","Back background color"],["اللوغو","Logo","Logo"],["صورة","Image","Image"],["النص","Texte","Text"],["إظهار عنصر الظهر","Afficher l’élément du verso","Show back element"],["موضع اللوغو","Position du logo","Logo position"],["حجم اللوغو","Taille du logo","Logo size"],["رفع صورة","Importer une image","Upload image"],["نص ظهر الشارة","Texte du verso","Back text"],["حجم نص الظهر","Taille du texte du verso","Back text size"],["لون نص الظهر","Couleur du texte du verso","Back text color"],["عرض عنصر الظهر","Largeur de l’élément du verso","Back element width"],["ارتفاع عنصر الظهر","Hauteur de l’élément du verso","Back element height"],["شفافية عنصر الظهر","Opacité de l’élément du verso","Back element opacity"],["Radius عنصر الظهر","Rayon de l’élément du verso","Back element radius"],["ظل عنصر الظهر","Ombre de l’élément du verso","Back element shadow"],["الحفاظ على نسبة اللوغو","Conserver les proportions du logo","Keep logo aspect ratio"],["الحفاظ على نسبة الصورة","Conserver les proportions de l’image","Keep image aspect ratio"],["إعادة موضع وحجم اللوغو","Réinitialiser la position et la taille du logo","Reset logo position and size"],["حذف العنصر","Supprimer l’élément","Delete element"],
  ["مظهر المكوّن","Apparence du composant","Component appearance"],["عادي","Normal","Normal"],["عائم","Flottant","Floating"],["ظل خفيف","Ombre légère","Soft shadow"],["ظل واضح","Ombre prononcée","Elevated shadow"],["تخصيص الظل المتقدم","Réglages avancés de l’ombre","Advanced shadow settings"],["طبقة بصرية مستقلة — لا تخفي الاسم أو الصورة","Couche visuelle indépendante — ne masque ni le nom ni la photo","Independent visual layer — does not hide the name or photo"],["إظهار الحاوية","Afficher le conteneur","Show container"],["إظهار حاوية الاسم والصورة","Afficher le conteneur du nom et de la photo","Show name and photo container"],["إظهار الإطار","Afficher le cadre","Show border"],["إظهار إطار الاسم والصورة","Afficher le cadre du nom et de la photo","Show name and photo border"],["إظهار الظل","Afficher l’ombre","Show shadow"],["إظهار ظل حاوية الاسم والصورة","Afficher l’ombre du conteneur","Show container shadow"],
  ["حدد العنصر مرة أخرى لقياس موضعه الذكي.","Sélectionnez à nouveau l’élément pour mesurer sa position intelligente.","Select the element again to measure its smart position."],["تخصيص يدوي","Personnalisation manuelle","Manual customization"],["ترتيب RUKN الذكي","Disposition intelligente RUKN","RUKN smart layout"],["تلقائي","Automatique","Automatic"],["↺ تلقائي","↺ Automatique","↺ Automatic"],["الموضع الأفقي","Position horizontale","Horizontal position"],["الموضع العمودي","Position verticale","Vertical position"],["العرض","Largeur","Width"],["الارتفاع","Hauteur","Height"],["الحجم","Taille","Size"],["عنوان الحقل","Libellé du champ","Field label"],["قيمة الحقل","Valeur du champ","Field value"],["حجم عنوان الحقل","Taille du libellé","Label font size"],["وزن عنوان الحقل","Graisse du libellé","Label weight"],["لون عنوان الحقل","Couleur du libellé","Label color"],["حجم قيمة الحقل","Taille de la valeur","Value font size"],["وزن قيمة الحقل","Graisse de la valeur","Value weight"],["لون قيمة الحقل","Couleur de la valeur","Value color"],["حجم النص","Taille du texte","Text size"],["وزن النص","Graisse du texte","Text weight"],["لون النص","Couleur du texte","Text color"],["الخلفية والإطار","Arrière-plan et bordure","Background and border"],["لون الخلفية","Couleur de fond","Background color"],["لون الإطار","Couleur de bordure","Border color"],["سماكة الإطار","Épaisseur de bordure","Border width"],["شكل الصورة","Forme de la photo","Photo shape"],["ناعم","Doux","Soft"],["مربع","Carré","Square"],["دائري","Circulaire","Circular"],["الشفافية","Opacité","Opacity"],["إرجاع إلى داخل الشارة","Ramener dans le badge","Move inside badge"],["إرجاع للمكان الافتراضي","Revenir à la position par défaut","Return to default position"],["الموضع نسبي إلى حاوية الحقل","Position relative au conteneur du champ","Position relative to the field container"],["موضع القيمة","Position de la valeur","Value position"],["موضع العنوان","Position du libellé","Label position"],["إعادة موضع القيمة","Réinitialiser la position de la valeur","Reset value position"],["إعادة موضع العنوان","Réinitialiser la position du libellé","Reset label position"],
  ["لون خلفية الشارة","Couleur de fond du badge","Badge background color"],["استعادة خلفية التصميم","Restaurer le fond du design","Restore design background"],["لون خلفية منطقة الاسم","Couleur de fond de la zone du nom","Name area background color"],["لون الفواصل","Couleur des séparateurs","Separator color"],["Radius الإطار","Rayon de bordure","Border radius"],["شفافية الحاوية","Opacité du conteneur","Container opacity"],["Padding الداخلي","Espacement interne","Inner padding"],["العناوين","Libellés","Labels"],["حجم عناوين الحقول","Taille des libellés","Label font size"],["لون عناوين الحقول","Couleur des libellés","Label color"],["القيم","Valeurs","Values"],["حجم قيم الحقول","Taille des valeurs","Value font size"],["لون قيم الحقول","Couleur des valeurs","Value color"],["خلفية الحقل","Fond du champ","Field background"],["لون حدود الحقل","Couleur de bordure du champ","Field border color"],["سماكة الحدود","Épaisseur de bordure","Border width"],["استدارة الحواف","Rayon des coins","Border radius"],["المسافة الداخلية","Espacement interne","Padding"],
  ["صورة المعتمر","Photo du pèlerin","Pilgrim photo"],["رقم الجواز","Numéro de passeport","Passport number"],["المجموعة","Groupe","Group"],["رقم الغرفة","Numéro de chambre","Room number"],["فندق مكة","Hôtel à La Mecque","Makkah hotel"],["فندق المدينة","Hôtel à Médine","Madinah hotel"],["المدينة","Ville","City"],["الهاتف","Téléphone","Phone"],["هاتف المؤطر","Téléphone de l’accompagnateur","Guide phone"],["تاريخ السفر","Date du voyage","Travel date"],["شعار الوكالة","Logo de l’agence","Agency logo"],["اسم الوكالة","Nom de l’agence","Agency name"],["اسم المعتمر","Nom du pèlerin","Pilgrim name"],
  ["إظهار العلامة المائية","Afficher le filigrane","Show watermark"],["الشعار غير متوفر","Logo indisponible","Logo unavailable"],["شعار الوكالة جاهز للاستخدام في الخلفية","Le logo de l’agence est prêt pour le filigrane","Agency logo is ready for the watermark"],["أضف شعار الوكالة أولا لاستخدام العلامة المائية","Ajoutez d’abord le logo de l’agence pour utiliser le filigrane","Add the agency logo first to use the watermark"],["تخصيص العلامة المائية","Personnaliser le filigrane","Customize watermark"],["مأخوذ من هوية الوكالة","Issu de l’identité de l’agence","From agency identity"],["لا يوجد شعار مرفوع","Aucun logo importé","No logo uploaded"],["اللون الرئيسي","Couleur principale","Primary color"],["هادئ","Calme","Calm"],["متوازن","Équilibré","Balanced"],["غني","Riche","Rich"],
  ["رجوع","Retour","Back"],["تقدم","Avancer","Forward"],["عنوان","Libellé","Label"],["قيمة","Valeur","Value"],["تخصيص العنصر","Personnaliser l’élément","Customize element"],["استعادة الترتيب الذكي","Restaurer la disposition intelligente","Restore smart layout"],["استعادة البداية","Restaurer l’état initial","Restore initial state"],["جاري تحميل الإعدادات…","Chargement des paramètres…","Loading settings…"],["تغييرات غير محفوظة","Modifications non enregistrées","Unsaved changes"],["تم الحفظ","Enregistré","Saved"],["جاري الحفظ…","Enregistrement…","Saving…"],["حفظ","Enregistrer","Save"],["رجوع عن تعديل","Annuler","Undo"],["إعادة تعديل","Rétablir","Redo"],["تعذر تحميل إعدادات هوية الشارة","Impossible de charger les paramètres du badge","Unable to load badge identity settings"],["تعذر حفظ إعدادات هوية الشارة","Impossible d’enregistrer les paramètres du badge","Unable to save badge identity settings"],["تم حفظ هوية الشارة","Identité du badge enregistrée","Badge identity saved"],["هل تريد استعادة تصميم بداية جلسة التحرير؟","Restaurer le design du début de cette session ?","Restore the design from the start of this editing session?"],["سيتم استعادة الترتيب الذكي لكل العناصر المخصصة. هل تريد المتابعة؟","La disposition intelligente sera restaurée pour tous les éléments personnalisés. Continuer ?","Smart layout will be restored for all customized elements. Continue?"],["سيتم تطبيق التصميم المحدد بتخطيطه المستقل. هل تريد المتابعة؟","Le design sélectionné sera appliqué avec sa propre disposition. Continuer ?","The selected design will be applied with its own layout. Continue?"],
  ["الشارة قابلة للتعديل مباشرة، وكل قالب يحتفظ بتخصيصاته المستقلة.","Le badge est directement modifiable et chaque modèle conserve ses propres personnalisations.","The badge is directly editable and each template keeps its own customizations."],["Agency Header","En-tête de l’agence","Agency Header"],["Hero / الاسم والصورة","Hero / nom et photo","Hero / name and photo"],["رفع صورة ظهر الشارة","Importer une image pour le verso","Upload back image"],["X الظهر","X du verso","Back X"],["Y الظهر","Y du verso","Back Y"],["إظهار العنصر","Afficher l’élément","Show element"],["الحفاظ على النسبة","Conserver les proportions","Keep aspect ratio"],["لون الفواصل","Couleur des séparateurs","Separator color"],["تخصيص العلامة المائية","Personnaliser le filigrane","Customize watermark"],
  ["تخصيص","Personnaliser","Customize"],["تحريك","Déplacer","Move"],["لا توجد صورة","Aucune photo","No photo"],["صورة ظهر الشارة","Image du verso","Back image"],["شعار RUKN","Logo RUKN","RUKN logo"],
  ["RUKN Signature","Signature RUKN","RUKN Signature"],["Editorial","Éditorial","Editorial"],["Centered Ceremony","Cérémonie centrée","Centered Ceremony"],["Passport Inspired","Inspiré du passeport","Passport Inspired"],["Minimal Air","Minimal Air","Minimal Air"],["Travel Tag","Étiquette de voyage","Travel Tag"],["Luxury White","Blanc luxueux","Luxury White"],["RUKN Future","RUKN Futur","RUKN Future"]
];

const translations=Object.freeze(Object.fromEntries(rows.map(([ar,fr,en])=>[ar,{ar,fr,en}])));
const translationEntries=Object.freeze(Object.entries(translations).sort((a,b)=>b[0].length-a[0].length));
const translatableProps=new Set(["aria-label","title","placeholder","alt","label","hint"]);

export function translateSmartBadgeText(value,lang="ar"){
  if(typeof value!=="string"||lang==="ar")return value;
  let result=value;
  translationEntries.forEach(([source,target])=>{result=result.split(source).join(target[lang]||source);});
  return result;
}

export function localizeSmartBadgeTree(node,lang){
  if(typeof node==="string")return translateSmartBadgeText(node,lang);
  if(!React.isValidElement(node))return node;
  if(node.props?.translate==="no"||node.props?.["data-i18n-skip"]===true)return node;
  const props={};
  translatableProps.forEach((key)=>{if(typeof node.props[key]==="string")props[key]=translateSmartBadgeText(node.props[key],lang);});
  if(Object.prototype.hasOwnProperty.call(node.props,"children"))props.children=React.Children.map(node.props.children,(child)=>localizeSmartBadgeTree(child,lang));
  return React.cloneElement(node,props);
}

export function useSmartBadgeI18n(){
  const {lang,dir}=useLang();
  return {lang,dir,text:React.useCallback((value)=>translateSmartBadgeText(value,lang),[lang]),tree:React.useCallback((node)=>localizeSmartBadgeTree(node,lang),[lang])};
}

export function SmartBadgeUi({children}){
  const {lang}=useLang();
  return localizeSmartBadgeTree(children,lang);
}

export const SMART_BADGE_UI_LANGUAGES=Object.freeze(["ar","fr","en"]);
