import React from "react";
import { getAgencyBrandingItems, getAgencyBrandingFooterItems, getAgencyBrandingFooterLines, getAgencyBrandingFooterGroups, getDocumentHeaderLayout, getDocumentIdentityLocaleLayout, getDocumentWatermarkLayout, normalizeDocumentBranding } from "./documentBranding";

export function AgencyDocumentHeader({ agency={}, config, title="", number="", lang="ar" }) {
  const normalized=normalizeDocumentBranding(config),layout=getDocumentHeaderLayout(normalized),localeLayout=getDocumentIdentityLocaleLayout(normalized,lang),items=getAgencyBrandingItems(agency,["logo","nameAr","nameLatin"].filter((key)=>normalized.visibleFields[key]),lang),byKey=Object.fromEntries(items.map((item)=>[item.key,item.value]));
  return <header className={`document-branding agency-branding-${normalized.style} identity-dir-${lang==='ar'?'rtl':'ltr'} ${localeLayout.classes} ${layout.classes}`} style={{"--agency-brand":normalized.brandColor,...layout.previewStyle}}><div className="document-branding-header agency-branding-header">{byKey.logo&&<img className="document-branding-logo" src={byKey.logo} alt="" onError={(event)=>event.currentTarget.remove()}/>}<div dir={lang==='ar'?'rtl':'ltr'} className="document-branding-agency-names agency-branding-names">{byKey.nameAr&&<strong className="document-branding-name">{byKey.nameAr}</strong>}{byKey.nameLatin&&<span className="document-branding-name-fr">{byKey.nameLatin}</span>}</div></div></header>;
}

const FooterEntry=({item})=><span className={`footer-entry field-${item.key}`}><span className="footer-label">{item.label} :</span> <bdi>{item.value}</bdi></span>;
const Interspersed=({items,separator,className})=><>{items.map((item,index)=><React.Fragment key={item.key}>{index>0&&<span className={className} aria-hidden="true"> {separator} </span>}<FooterEntry item={item}/></React.Fragment>)}</>;

export function AgencyDocumentFooter({agency={},config}){
  const normalized=normalizeDocumentBranding(config),items=getAgencyBrandingFooterItems(agency,normalized),density=items.length<=3?'compact':items.length>=6?'dense':'balanced';
  if(!items.length)return null;
  const common={dir:"ltr","data-footer-count":items.length,"data-footer-template":normalized.footerTemplate,"data-footer-composition":normalized.footerTemplate,className:`agency-branding-footer agency-branding-${normalized.style} ${normalized.footerTemplate} is-${density}`,style:{"--agency-brand":normalized.brandColor}};
  if(normalized.footerTemplate==='footer1'){const lines=getAgencyBrandingFooterLines(agency,normalized);return <footer {...common} data-footer-lines={lines.length}>{lines.map((line,index)=><span className="footer-line" key={`line-${index}`}><Interspersed items={line} separator="-" className="footer-separator"/></span>)}</footer>;}
  if(normalized.footerTemplate==='footer2'){return <footer {...common}><span className="footer2-inline"><Interspersed items={getAgencyBrandingFooterLines(agency,normalized).flat()} separator="•" className="footer2-dot"/></span></footer>;}
  if(normalized.footerTemplate==='footer3'){const groups=getAgencyBrandingFooterGroups(agency,normalized);return <footer {...common}><span className="footer3-groups">{groups.map((group,index)=><React.Fragment key={group.key}>{index>0&&<span className="footer3-divider" aria-hidden="true"/>}<span className={`footer3-group group-${group.key}`}><small>{group.label}</small><span><Interspersed items={group.items} separator="·" className="footer3-item-dot"/></span></span></React.Fragment>)}</span></footer>;}
  return <footer {...common}><span className="footer4-strip-content"><Interspersed items={getAgencyBrandingFooterLines(agency,normalized).flat()} separator="•" className="footer4-separator"/></span></footer>;
}

function InvoiceSample({t}){return <main className="document-sample sample-invoice"><div className="agency-branding-sample-title">{t.brandingInvoice}</div><div className="agency-sample-meta"><div className="agency-sample-box"><strong>{t.brandingSampleClient}</strong>{t.brandingSampleClient}<br/>{t.brandingSampleCity}</div><div className="agency-sample-box"><strong>{t.brandingSampleDetails}</strong>{t.brandingSampleDate}: 11/08/2026<br/>{t.brandingSampleReference}</div></div><SampleTable t={t}/><div className="agency-sample-total"><span>{t.brandingSampleTotal}</span><strong>1,250.00 MAD</strong></div></main>;}
function ReceiptSample({t}){return <main className="document-sample sample-receipt"><div className="receipt-number">N° R-2026-014</div><div className="agency-branding-sample-title">{t.brandingReceipt}</div><section className="receipt-details"><p><strong>{t.brandingSamplePayment}</strong><span>{t.brandingSampleClient}</span></p><p><strong>{t.brandingSampleAmount}</strong><span className="receipt-amount">1,250.00 MAD</span></p><p><strong>{t.brandingSamplePaymentMethod||"Payment method"}</strong><span>{t.brandingSamplePaymentMethodValue||"Bank transfer"}</span></p><p><strong>{t.brandingSampleDate}</strong><span>11/08/2026</span></p></section><div className="receipt-signature">{t.brandingSampleSignature||"Signature"}</div></main>;}
function ContractSample({t}){return <main className="document-sample sample-contract"><div className="agency-branding-sample-title">{t.brandingContract}</div><p className="contract-intro">{t.brandingSampleContractIntro||"This agreement is concluded between the agency and the traveler according to the terms below."}</p><section><strong>01</strong><p>{t.brandingSampleClauseOne||"Travel services, dates and included benefits are defined in the confirmed program."}</p></section><section><strong>02</strong><p>{t.brandingSampleClauseTwo||"Both parties acknowledge and accept the payment and cancellation conditions."}</p></section><div className="contract-signatures"><span>{t.brandingSampleAgencySignature||"Agency signature"}</span><span>{t.brandingSampleClientSignature||"Client signature"}</span></div></main>;}
function ListSample({t}){return <main className="document-sample sample-list"><div className="agency-branding-sample-title">{t.brandingList}</div><table className="agency-sample-table"><thead><tr><th>#</th><th>{t.brandingSampleClient}</th><th>{t.brandingSampleCity}</th><th>{t.brandingSampleReference}</th></tr></thead><tbody>{[1,2,3,4].map((row)=><tr key={row}><td>{row}</td><td>{t.brandingSampleClient} {row}</td><td>{t.brandingSampleCity}</td><td>REF-00{row}</td></tr>)}</tbody></table></main>;}
function ReportSample({t}){return <main className="document-sample sample-report"><div className="agency-branding-sample-title">{t.brandingReport}</div><div className="report-metrics"><span><small>{t.brandingSampleReportClients||"Clients"}</small><strong>48</strong></span><span><small>{t.brandingSampleReportPaid||"Paid"}</small><strong>82%</strong></span><span><small>{t.brandingSampleReportBalance||"Balance"}</small><strong>24,500 MAD</strong></span></div><div className="report-content"><section><strong>{t.brandingSampleDetails}</strong><p>{t.brandingSampleReportText||"Compact operational summary for the selected period."}</p></section><SampleTable t={t} compact/></div></main>;}
function SampleTable({t,compact=false}){return <table className={`agency-sample-table${compact?' is-compact':''}`}><thead><tr><th>{t.brandingSampleDescription}</th><th>{t.brandingSampleQuantity}</th><th>{t.brandingSampleAmount}</th></tr></thead><tbody><tr><td>{t.brandingSampleService}</td><td>1</td><td>1,000.00</td></tr><tr><td>{t.brandingSampleExtra}</td><td>1</td><td>250.00</td></tr></tbody></table>;}
const Samples={invoice:InvoiceSample,receipt:ReceiptSample,contract:ContractSample,list:ListSample,report:ReportSample};

export function AgencyDocumentBranding({agency={},config,documentType="invoice",t,lang="ar",dir="rtl"}){
  const normalized=normalizeDocumentBranding(config),layout=getDocumentHeaderLayout(normalized),watermarkLayout=getDocumentWatermarkLayout(normalized),labels={invoice:t.brandingInvoice,receipt:t.brandingReceipt,contract:t.brandingContract,list:t.brandingList,report:t.brandingReport},Sample=Samples[documentType]||InvoiceSample,isPlain=config?.enabled===false,logo=agency.logoUrl||agency.logo_url;
  const zoomLayerRef=React.useRef(null),frameRef=React.useRef(0),pointerRef=React.useRef(null);
  const applyZoomOrigin=React.useCallback(()=>{frameRef.current=0;const point=pointerRef.current,zoomLayer=zoomLayerRef.current;if(!point||!zoomLayer)return;zoomLayer.style.setProperty('--preview-zoom-x',`${point.x.toFixed(2)}%`);zoomLayer.style.setProperty('--preview-zoom-y',`${point.y.toFixed(2)}%`);},[]);
  const trackZoomOrigin=(event)=>{const rect=event.currentTarget.getBoundingClientRect();if(!rect.width||!rect.height)return;pointerRef.current={x:Math.max(0,Math.min(100,((event.clientX-rect.left)/rect.width)*100)),y:Math.max(0,Math.min(100,((event.clientY-rect.top)/rect.height)*100))};if(!frameRef.current)frameRef.current=requestAnimationFrame(applyZoomOrigin);};
  const resetZoomOrigin=()=>{pointerRef.current=null;if(frameRef.current)cancelAnimationFrame(frameRef.current);frameRef.current=0;zoomLayerRef.current?.style.setProperty('--preview-zoom-x','50%');zoomLayerRef.current?.style.setProperty('--preview-zoom-y','50%');};
  React.useEffect(()=>()=>{if(frameRef.current)cancelAnimationFrame(frameRef.current);},[]);
  return <div data-preview-viewport className="agency-branding-preview-viewport" onPointerMove={trackZoomOrigin} onPointerLeave={resetZoomOrigin}><div data-preview-fit-layer className="agency-branding-preview-fit-layer"><div ref={zoomLayerRef} data-preview-zoom-layer className="agency-branding-preview-zoom-layer"><div data-preview-paper data-orientation={normalized.orientation} data-document-type={documentType} data-template={normalized.style} data-branding-state={isPlain?'plain':'branded'} className={`agency-branding-preview is-${normalized.orientation} is-${documentType} design-${normalized.style}${isPlain?' is-plain':''}`} style={{...layout.previewStyle,...watermarkLayout.previewStyle,"--agency-brand":normalized.brandColor}} dir={dir} lang={lang}>{!isPlain&&normalized.watermark.enabled&&logo&&<img data-document-watermark className="document-branding-watermark" src={logo} alt="" aria-hidden="true" onError={(event)=>event.currentTarget.remove()}/>} {!isPlain&&<AgencyDocumentHeader agency={agency} config={normalized} lang={lang}/>}<Sample t={t}/>{!isPlain&&<AgencyDocumentFooter agency={agency} config={normalized}/>}</div></div></div></div>;
}
