import React, { act } from "react";
import fs from "fs";
import path from "path";
import { createRoot } from "react-dom/client";
import { AgencyDocumentBranding } from "./AgencyDocumentBranding";
import { TRANSLATIONS } from "../../data/initialData";

describe("document branding preview paper", () => {
  let host; let root;
  beforeEach(()=>{global.IS_REACT_ACT_ENVIRONMENT=true;host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);});
  afterEach(async()=>{await act(async()=>root.unmount());host.remove();delete global.IS_REACT_ACT_ENVIRONMENT;});
  const render=async(orientation="portrait",lang="ar")=>act(async()=>root.render(<AgencyDocumentBranding agency={{nameAr:"وكالة",logoUrl:"https://example.test/real-logo.png",email:"info@example.test"}} config={{orientation,visibleFields:{logo:true,nameAr:true,email:true}}} t={TRANSLATIONS[lang]} lang={lang} dir={lang==='ar'?'rtl':'ltr'}/>));

  test("portrait preview receives the physical branding variables used by A4",async()=>{await render("portrait");const paper=host.querySelector("[data-preview-paper]");expect(paper.dataset.orientation).toBe("portrait");expect(paper.style.getPropertyValue("--branding-logo-size")).toBe("22mm");expect(paper.style.getPropertyValue("--branding-name-size")).toBe("20pt");});
  test("landscape preserves the same physical variables",async()=>{await render("landscape");const paper=host.querySelector("[data-preview-paper]");expect(paper.classList.contains("is-landscape")).toBe(true);expect(paper.style.getPropertyValue("--branding-logo-size")).toBe("22mm");});
  test("switching orientation preserves the same preview paper and real logo",async()=>{await render("portrait");const first=host.querySelector("[data-preview-paper]");await render("landscape");expect(host.querySelector("[data-preview-paper]")).toBe(first);expect(host.querySelector("img").src).toBe("https://example.test/real-logo.png");});
  test("preview contains readable sample content instead of skeleton bars",async()=>{await render();expect(host.textContent).toContain("عميل تجريبي");expect(host.textContent).toContain("1,250.00 MAD");expect(host.querySelector("table")).not.toBeNull();});
  test("French and English previews use LTR and translated content",async()=>{await render("portrait","fr");expect(host.querySelector("[data-preview-paper]").dir).toBe("ltr");expect(host.textContent).toContain("Facture");expect(host.textContent).toContain("Désignation");await render("portrait","en");expect(host.textContent).toContain("Invoice");expect(host.textContent).toContain("Description");});
  test("preview header uses the same semantic composition and physical tokens as print",async()=>{await act(async()=>root.render(<AgencyDocumentBranding agency={{nameAr:"وكالة",logoUrl:"logo.png"}} config={{headerLogoSize:38,headerNameSize:28,headerAlign:"center",headerPlacement:"stacked",headerDivider:false}} t={TRANSLATIONS.ar} lang="ar" dir="rtl"/>));const paper=host.querySelector("[data-preview-paper]"),shell=host.querySelector("header.document-branding"),header=shell.querySelector(".document-branding-header");expect(shell.classList.contains("header-placement-stacked")).toBe(true);expect(shell.classList.contains("header-align-center")).toBe(true);expect(shell.classList.contains("header-no-divider")).toBe(true);expect(paper.style.getPropertyValue("--branding-logo-size")).toBe("38mm");expect(paper.style.getPropertyValue("--branding-name-size")).toBe("28pt");expect(header.querySelector(".document-branding-logo")).not.toBeNull();expect(header.querySelector(".document-branding-name").textContent).toBe("وكالة");});
  test("top-space updates live on preview without changing logo or agency-name sizing",async()=>{const draw=async(headerDensity)=>act(async()=>root.render(<AgencyDocumentBranding agency={{nameAr:"وكالة",logoUrl:"logo.png"}} config={{headerDensity,headerLogoSize:22,headerNameSize:20}} t={TRANSLATIONS.ar} lang="ar" dir="rtl"/>));const values=[];for(const headerDensity of [14,27,40]){await draw(headerDensity);const paper=host.querySelector("[data-preview-paper]");values.push(parseFloat(paper.style.getPropertyValue("--branding-top-space")));expect(paper.style.getPropertyValue("--branding-logo-size")).toBe("22mm");expect(paper.style.getPropertyValue("--branding-name-size")).toBe("20pt");}expect(values[1]).toBeGreaterThan(values[0]);expect(values[2]).toBeGreaterThan(values[1]);});
  test.each([["ar","rtl","وكالة الأسفار والسياحة دار الإيمان"],["en","ltr","Dar Al Iman Travel and Tourism Agency"]])("%s long identity remains complete in %s",async(lang,dir,name)=>{const agency=lang==='ar'?{nameAr:name,logoUrl:"logo.png"}:{agencyNameLatin:name,logoUrl:"logo.png"};await act(async()=>root.render(<AgencyDocumentBranding agency={agency} config={{headerLogoSize:"xlarge",headerNameSize:"xlarge",headerPlacement:"inline-start"}} t={TRANSLATIONS[lang]} lang={lang} dir={dir}/>));const paper=host.querySelector("[data-preview-paper]"),nameNode=host.querySelector(".document-branding-name, .document-branding-name-fr");expect(paper.dir).toBe(dir);expect(nameNode.textContent).toBe(name);expect(nameNode.textContent).not.toContain("...");expect(host.querySelector(".document-branding-logo")).not.toBeNull();});
  test("Arabic preview stays RTL while its footer is Latin and LTR",async()=>{const config={footerTemplate:"footer1",visibleFields:{nameAr:true,nameLatin:true,address1:true,email:true,website:true}};await act(async()=>root.render(<AgencyDocumentBranding agency={{nameAr:"وكالة عربية",agencyNameLatin:"Latin Agency",addressPrimaryAr:"عنوان عربي",addressPrimaryLatin:"Latin address",email:"mail@example.test",website:"example.test"}} config={config} t={TRANSLATIONS.ar} lang="ar" dir="rtl"/>));const paper=host.querySelector("[data-preview-paper]"),footer=host.querySelector("[data-footer-lines]");expect(paper.dir).toBe("rtl");expect(footer.dir).toBe("ltr");expect(footer.textContent).toContain("Adresse : Latin address");expect(footer.textContent).not.toContain("عنوان عربي");expect(footer.textContent.indexOf("mail@example.test")).toBeLessThan(footer.textContent.indexOf("example.test"));expect(footer.querySelectorAll("bdi").length).toBeGreaterThan(0);await act(async()=>root.render(<AgencyDocumentBranding agency={{nameAr:"وكالة عربية",agencyNameLatin:"Latin Agency",addressPrimaryAr:"عنوان عربي",addressPrimaryLatin:"Latin address"}} config={config} t={TRANSLATIONS.en} lang="en" dir="ltr"/>));expect(host.textContent).toContain("Latin Agency");expect(host.querySelector("footer").textContent).toContain("Latin address");});
  test("fixed viewport updates paper origin through animation frame and leave resets it",async()=>{await render();const viewport=host.querySelector("[data-preview-viewport]"),paper=host.querySelector("[data-preview-zoom-layer]");viewport.getBoundingClientRect=()=>({left:10,top:20,width:200,height:300,right:210,bottom:320});const move=new Event("pointermove",{bubbles:true});Object.defineProperties(move,{clientX:{value:160},clientY:{value:260}});await act(async()=>{viewport.dispatchEvent(move);await new Promise((resolve)=>requestAnimationFrame(resolve));});expect(paper.style.getPropertyValue("--preview-zoom-x")).toBe("75.00%");expect(paper.style.getPropertyValue("--preview-zoom-y")).toBe("80.00%");await act(async()=>viewport.dispatchEvent(new Event("pointerout",{bubbles:true})));expect(paper.style.getPropertyValue("--preview-zoom-x")).toBe("50%");expect(paper.style.getPropertyValue("--preview-zoom-y")).toBe("50%");});
  test("zoom transforms only the paper while its viewport remains fixed and non-reflowing",()=>{const css=fs.readFileSync(path.resolve(__dirname,"documentBrandingPreviewZoom.css"),"utf8"),layout=fs.readFileSync(path.resolve(__dirname,"documentBrandingRanges.css"),"utf8");expect(layout).toContain("agency-branding-preview-fit-layer{position:absolute");expect(layout).toContain("transform:scale(var(--preview-paper-scale));transform-origin:0 0");expect(css).toContain(".agency-branding-preview-viewport:hover .agency-branding-preview-zoom-layer");expect(css).toContain("transform: scale(1.5)");expect(css).toContain("pointer-events: none");expect(css).not.toMatch(/:hover[^}]*width:/);expect(css).not.toMatch(/:hover[^}]*height:/);});
  test.each([[0,0],[1,0],[.5,.5],[0,1],[1,1]])("cursor anchor %s,%s remains fixed after fit and zoom",(x,y)=>{const fit=.4,zoom=1.5,width=210,height=297,cursor={x:x*width*fit,y:y*height*fit},origin={x:x*width,y:y*height},logical={x:cursor.x/fit,y:cursor.y/fit},projected={x:(origin.x+(logical.x-origin.x)*zoom)*fit,y:(origin.y+(logical.y-origin.y)*zoom)*fit};expect(projected.x).toBeCloseTo(cursor.x);expect(projected.y).toBeCloseTo(cursor.y);});
  test("A4 paper root owns uniform scale while body keeps print-like typography",()=>{const layout=fs.readFileSync(path.resolve(__dirname,"documentBrandingRanges.css"),"utf8"),base=fs.readFileSync(path.resolve(__dirname,"documentBranding.css"),"utf8");expect(layout).toContain("width:210mm;height:297mm");expect(layout).toContain("width:297mm;height:210mm");expect(layout).toContain("--preview-paper-scale:.4");expect(base).toContain("main{flex:0 0 auto;padding:4mm .5mm;min-height:auto");expect(base).toContain(".agency-sample-table{width:100%;border-collapse:collapse;font-size:8.5pt}");expect(base).not.toMatch(/agency-branding-preview main[^}]*transform/);expect(layout).not.toContain("agency-branding-preview main");});
  test("zoom mapping is direct on both axes with no inversion or scale compensation",()=>{const source=fs.readFileSync(path.resolve(__dirname,"AgencyDocumentBranding.jsx"),"utf8");expect(source).toContain("(event.clientX-rect.left)/rect.width");expect(source).toContain("(event.clientY-rect.top)/rect.height");expect(source).not.toMatch(/1\s*-\s*\(?\(?event\.clientY/);expect(source).not.toMatch(/client[XY][^;]*preview-paper-scale/);});
  test.each([["invoice","sample-invoice","agency-sample-table"],["receipt","sample-receipt","receipt-details"],["contract","sample-contract","contract-signatures"],["list","sample-list","agency-sample-table"],["report","sample-report","report-metrics"]])("%s renders a document-specific sample composition",async(type,sampleClass,landmark)=>{await act(async()=>root.render(<AgencyDocumentBranding agency={{addressPrimaryLatin:"Latin"}} config={{enabled:true,footerTemplate:"footer3"}} documentType={type} t={TRANSLATIONS.en} lang="en" dir="ltr"/>));expect(host.querySelector(`[data-document-type="${type}"]`)).not.toBeNull();expect(host.querySelector(`.${sampleClass}`)).not.toBeNull();expect(host.querySelector(`.${landmark}`)).not.toBeNull();expect(host.querySelector('[data-footer-composition="footer3"]')).not.toBeNull();});
  test("footer design 3 renders selected visible agency groups without visibility patches",async()=>{await act(async()=>root.render(<AgencyDocumentBranding agency={{addressPrimaryLatin:"Latin address",phoneTiznit1:"0500",email:"mail@example.test",website:"example.test",rc:"12",ice:"34"}} config={{enabled:true,footerTemplate:"footer3",visibleFields:{address1:true,phone1:true,email:true,website:true,rc:true,ice:true}}} documentType="invoice" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));const footer=host.querySelector('[data-footer-composition="footer3"]');expect(footer).not.toBeNull();expect(footer.textContent).toContain("Latin address");expect(footer.textContent).toContain("mail@example.test");expect(footer.textContent).toContain("R.C");expect(footer.textContent).toContain("12");expect(footer.textContent).toContain("ICE");expect(footer.textContent).toContain("34");const css=fs.readFileSync(path.resolve(__dirname,"documentBrandingFooter.css"),"utf8");expect(css).not.toContain("visibility: visible");expect(css).not.toContain("opacity: 1");expect(css).not.toContain("overflow: visible");});
  test.each(["minimal","modern","formal"])("all footer templates remain present with document design %s",async(style)=>{for(const footerTemplate of ["footer1","footer2","footer3","footer4"]){await act(async()=>root.render(<AgencyDocumentBranding agency={{agencyNameLatin:"Agency",addressPrimaryLatin:"Latin address",phoneTiznit1:"0500",email:"mail@example.test",website:"example.test",rc:"12",ice:"34"}} config={{enabled:true,style,footerTemplate,visibleFields:{nameLatin:true,address1:true,phone1:true,email:true,website:true,rc:true,ice:true}}} documentType="invoice" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));const footer=host.querySelector("footer");expect(footer).not.toBeNull();expect(footer.dataset.footerTemplate).toBe(footerTemplate);expect(footer.textContent).toContain("Latin address");expect(footer.previousElementSibling.tagName).toBe("MAIN");}});
  test("document labels use A/B/C while footer labels keep numeric identities",()=>{expect(TRANSLATIONS.ar.brandingDesign1).toBe("تصميم A");expect(TRANSLATIONS.fr.brandingDesign2).toBe("Design B");expect(TRANSLATIONS.en.brandingDesign3).toBe("Design C");expect(TRANSLATIONS.en.brandingFooterDesign1).toMatch(/1/);expect(TRANSLATIONS.en.brandingFooterDesign4).toMatch(/4/);});
  test("orientation changes preserve the sample type and shared zoom paper",async()=>{await act(async()=>root.render(<AgencyDocumentBranding agency={{}} config={{enabled:false,orientation:"portrait"}} documentType="report" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));const paper=host.querySelector("[data-preview-paper]");expect(paper.querySelector(".sample-report")).not.toBeNull();await act(async()=>root.render(<AgencyDocumentBranding agency={{}} config={{enabled:false,orientation:"landscape"}} documentType="report" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));expect(host.querySelector("[data-preview-paper]")).toBe(paper);expect(paper.classList.contains("is-landscape")).toBe(true);expect(paper.querySelector(".report-content")).not.toBeNull();});
});
