import React, { act } from "react";
import fs from "fs";
import path from "path";
import { createRoot } from "react-dom/client";
import { TRANSLATIONS } from "../../data/initialData";
import DocumentBrandingSettings, { getBrandingPreviewFollowOffset } from "./DocumentBrandingSettings";

describe("document branding settings i18n",()=>{let host;let root;beforeEach(()=>{global.IS_REACT_ACT_ENVIRONMENT=true;host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);});afterEach(async()=>{await act(async()=>root.unmount());host.remove();delete global.IS_REACT_ACT_ENVIRONMENT;});
  const value={enabled:true,applyToAll:true,defaultProfile:{style:"minimal",orientation:"portrait",colorMode:"manual",brandColor:"#123456"},documents:{invoice:{mode:"inherit"}}};
  const render=async(lang)=>act(async()=>root.render(<DocumentBrandingSettings agency={{nameAr:"وكالة"}} value={value} onChange={()=>{}} logoUrl="https://example.test/logo.png" t={TRANSLATIONS[lang]} lang={lang} dir={lang==='ar'?'rtl':'ltr'}/>));
  test("AR to FR updates controls and preview immediately",async()=>{await render("ar");expect(host.textContent).toContain("طريقة الطباعة");expect(host.textContent).toContain("فاتورة");expect(host.firstChild.dir).toBe("rtl");await render("fr");expect(host.textContent).toContain("Mode d’impression");expect(host.textContent).toContain("Facture");expect(host.textContent).not.toContain("طريقة الطباعة");expect(host.firstChild.dir).toBe("ltr");});
  test("UI exposes dedicated header controls and the existing visibility checkboxes",async()=>{await render("en");const rows=[...host.querySelectorAll(".branding-folded-trigger")],header=rows.find((row)=>row.textContent.includes("Top-of-page layout")),data=rows.find((row)=>row.textContent.includes("Displayed data"));await act(async()=>header.click());expect(host.textContent).toContain("Logo size");expect(host.textContent).toContain("Agency name size");expect(host.textContent).toContain("Logo and name order");expect(host.textContent).toContain("Show line below identity");await act(async()=>data.click());expect(host.querySelectorAll('.branding-elements-grid input[type="checkbox"]').length).toBe(17);expect(host.querySelectorAll(".branding-folded-sheet").length).toBe(4);});
  test("watermark exposes the shared accessible sliders and safe ranges",async()=>{await render("en");const row=[...host.querySelectorAll(".branding-folded-trigger")].find((item)=>item.textContent.includes("Watermark"));expect(row.textContent).toContain("110mm · 10%");await act(async()=>row.click());const size=host.querySelector('[aria-label="Watermark size"]'),opacity=host.querySelector('[aria-label="Watermark opacity"]');expect(size.min).toBe("40");expect(size.max).toBe("320");expect(opacity.min).toBe("0");expect(opacity.max).toBe("100");expect(host.textContent).toContain("Show watermark");});
  test("header labels are user-facing and sliders expose numeric live controls",async()=>{await render("ar");const row=[...host.querySelectorAll(".branding-folded-trigger")].find((item)=>item.textContent.includes("شكل أعلى الورقة"));await act(async()=>row.click());expect(host.textContent).toContain("حجم بيانات أسفل الورقة");const sliders=row.closest(".branding-folded-sheet").querySelectorAll('input[type="range"]');expect(sliders).toHaveLength(5);expect(host.querySelector('[aria-label="حجم الشعار"]').max).toBe("42");expect(host.querySelector('[aria-label="حجم اسم الوكالة"]').max).toBe("34");expect(host.querySelector('[aria-label="مساحة أعلى الورقة"]').max).toBe("40");expect(host.querySelector('[aria-label="المسافة بين الشعار والاسم"]').max).toBe("14");expect(host.querySelector('[aria-label="حجم بيانات أسفل الورقة"]').max).toBe("15");});
  test("top-of-page sheet gives sliders calm horizontal breathing room",()=>{const css=fs.readFileSync(path.resolve(__dirname,"documentBrandingRanges.css"),"utf8");expect(css).toContain(".branding-header-sheet .branding-folded-content{padding:14px 18px 16px}");expect(css).toContain(".branding-header-sheet .branding-range-control{margin-inline:4px;padding:11px 4px}");expect(css).not.toContain(".branding-header-sheet .branding-range-control{width:100vw");});
  test("preview uses an independent follow layer without sticky or fixed positioning",()=>{const layout=fs.readFileSync(path.resolve(__dirname,"documentBrandingRanges.css"),"utf8"),progressive=fs.readFileSync(path.resolve(__dirname,"documentBrandingProgressive.css"),"utf8");expect(layout).toContain(".branding-settings-editor .branding-preview-column{position:relative;align-self:stretch");expect(layout).toContain(".branding-settings-editor .branding-preview-follow-layer{position:relative;will-change:transform}");expect(progressive).toContain(".branding-settings-editor .branding-preview-follow-layer { transform: none !important; will-change: auto; }");expect(layout).not.toContain("position:sticky");expect(layout).not.toContain("position:fixed");});
  test("follow offset tracks scroll and clamps inside both branding boundaries",()=>{expect(getBrandingPreviewFollowOffset({sectionTop:100,sectionHeight:1000,previewHeight:490})).toBe(0);expect(getBrandingPreviewFollowOffset({sectionTop:-200,sectionHeight:1000,previewHeight:490})).toBe(216);expect(getBrandingPreviewFollowOffset({sectionTop:-900,sectionHeight:1000,previewHeight:490})).toBe(494);expect(getBrandingPreviewFollowOffset({sectionTop:-10,sectionHeight:400,previewHeight:490})).toBe(0);});
  test("folded rows share compact padding and a safe chevron hit area",()=>{const css=fs.readFileSync(path.resolve(__dirname,"documentBrandingProgressive.css"),"utf8");expect(css).toContain("min-height: 38px");expect(css).toContain("padding: 4px 9px");expect(css).toContain("height: 22px");expect(css).toContain('[dir="rtl"] .branding-folded-action');});
  test("expanded watermark controls use compact spacing without shrinking sliders",()=>{const css=fs.readFileSync(path.resolve(__dirname,"documentBrandingRanges.css"),"utf8");expect(css).toContain(".branding-watermark-sheet.is-open .branding-folded-content{padding:8px 12px 10px}");expect(css).toContain(".branding-watermark-sheet .branding-header-controls{gap:0}");expect(css).toContain(".branding-watermark-sheet .branding-range-control{gap:6px;margin-inline:2px;padding:7px 2px}");expect(css).toContain("input::-webkit-slider-thumb{appearance:none;width:16px;height:16px");});

  test("identity position uses accessible right center left icons without start/end UX",async()=>{await render("en");const row=[...host.querySelectorAll(".branding-folded-trigger")].find((item)=>item.textContent.includes("Top-of-page layout"));await act(async()=>row.click());const group=host.querySelector('.branding-alignment-icons');expect(group.querySelectorAll("svg")).toHaveLength(3);expect(group.querySelector('[aria-label="Right"]')).not.toBeNull();expect(group.querySelector('[aria-label="Center"]')).not.toBeNull();expect(group.querySelector('[aria-label="Left"]')).not.toBeNull();expect(group.textContent).not.toContain("Start");expect(group.textContent).not.toContain("End");expect(group.querySelector('[aria-pressed="true"]')).not.toBeNull();});
  test("segmented selector exposes one reusable high-contrast selected state",async()=>{await render("en");const selected=host.querySelector('.branding-segment.is-selected');const unselected=host.querySelector('.branding-segment:not(.is-selected)');expect(selected.getAttribute("aria-pressed")).toBe("true");expect(selected.style.color).toBe("rgb(255, 255, 255)");expect(unselected.getAttribute("aria-pressed")).toBe("false");expect(unselected.style.background).toBe("transparent");});
  test("print data row shows a smart enabled count and opens from the whole row",async()=>{await render("ar");const row=[...host.querySelectorAll(".branding-folded-trigger")].find((item)=>item.textContent.includes("بيانات المطبوع"));expect(row.textContent).toMatch(/\d+ مفعلة/);expect(row.textContent).toContain("الشعار");await act(async()=>row.click());expect(row.getAttribute("aria-expanded")).toBe("true");expect(host.querySelectorAll('.branding-elements-grid input[type="checkbox"]').length).toBe(17);});
  test("documents expose five direct binary choices and a clear all-documents control",async()=>{const changed=jest.fn();await act(async()=>root.render(<DocumentBrandingSettings agency={{nameAr:"وكالة"}} value={value} onChange={changed} logoUrl="" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));const trigger=host.querySelector(".branding-documents-sheet .branding-folded-trigger");expect(trigger.textContent).toContain("All documents use agency identity");await act(async()=>trigger.click());const sheet=host.querySelector(".branding-documents-sheet");expect(sheet.querySelectorAll(".branding-document-mode-row")).toHaveLength(6);for(const label of ["Invoice","Receipt","Contract","List","Report"])expect(sheet.textContent).toContain(label);expect(sheet.textContent).toContain("Apply to all");expect(sheet.querySelectorAll(".branding-document-mode-row .branding-segment")).toHaveLength(12);expect(sheet.textContent).not.toMatch(/Customize document|No identity|Edit|\binherit\b|\bcustom\b|\boff\b/);const contract=[...sheet.querySelectorAll(".branding-document-mode-row")].find((row)=>row.textContent.includes("Contract"));await act(async()=>contract.querySelectorAll('button')[0].click());expect(changed.mock.calls.at(-1)[0].documents.contract.mode).toBe("off");const applyAll=sheet.querySelector(".branding-document-mode-row.is-all");await act(async()=>applyAll.querySelectorAll('button')[0].click());expect(Object.values(changed.mock.calls.at(-1)[0].documents).every((entry)=>entry.mode==='off')).toBe(true);});
  test("mixed document state has no misleading apply-all selection and a human summary",async()=>{const mixed={...value,documents:{invoice:{mode:"inherit"},receipt:{mode:"off"},contract:{mode:"inherit"},list:{mode:"off"},report:{mode:"custom",profile:{style:"formal"}}}};await act(async()=>root.render(<DocumentBrandingSettings agency={{nameAr:"وكالة"}} value={mixed} onChange={()=>{}} logoUrl="" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));const trigger=host.querySelector(".branding-documents-sheet .branding-folded-trigger");expect(trigger.textContent).toContain("Different settings by document");await act(async()=>trigger.click());const all=host.querySelector(".branding-document-mode-row.is-all");expect(all.textContent).toContain("Different settings by document");expect(all.querySelectorAll('[aria-pressed="true"]')).toHaveLength(0);});
  test("preview selector defaults to invoice and switches all five connected samples without persisting",async()=>{const changed=jest.fn();await act(async()=>root.render(<DocumentBrandingSettings agency={{nameAr:"وكالة",addressPrimaryLatin:"Latin"}} value={value} onChange={changed} logoUrl="" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));const select=host.querySelector(".branding-preview-selector select");expect(select.value).toBe("invoice");expect(host.querySelector("[data-document-type]").dataset.documentType).toBe("invoice");for(const type of ["receipt","contract","list","report"]){await act(async()=>{select.value=type;select.dispatchEvent(new Event("change",{bubbles:true}));});expect(host.querySelector("[data-document-type]").dataset.documentType).toBe(type);expect(host.querySelector(`.sample-${type}`)).not.toBeNull();}expect(changed).not.toHaveBeenCalled();expect([...select.options]).toHaveLength(5);expect([...select.options].find((option)=>option.value==='contract').textContent).not.toContain("Preview");});
  test("preview resolves custom, inherited and off document modes",async()=>{const configured={...value,documents:{invoice:{mode:"inherit"},receipt:{mode:"custom",profile:{style:"formal",orientation:"landscape"}},contract:{mode:"off"}}};await act(async()=>root.render(<DocumentBrandingSettings agency={{nameAr:"وكالة"}} value={configured} onChange={()=>{}} logoUrl="" t={TRANSLATIONS.en} lang="en" dir="ltr"/>));const select=host.querySelector(".branding-preview-selector select");await act(async()=>{select.value='receipt';select.dispatchEvent(new Event("change",{bubbles:true}));});expect(host.querySelector("[data-preview-paper]").dataset.template).toBe("formal");expect(host.querySelector("[data-preview-paper]").dataset.orientation).toBe("landscape");await act(async()=>{select.value='contract';select.dispatchEvent(new Event("change",{bubbles:true}));});expect(host.querySelector("[data-preview-paper]").dataset.brandingState).toBe("plain");expect(host.querySelector(".agency-branding-header")).toBeNull();await act(async()=>{select.value='invoice';select.dispatchEvent(new Event("change",{bubbles:true}));});expect(host.querySelector("[data-preview-paper]").dataset.brandingState).toBe("branded");});
});
