import React,{act} from "react";
import {createRoot} from "react-dom/client";
import {AgencyDocumentBranding} from "./AgencyDocumentBranding";
import {TRANSLATIONS} from "../../data/initialData";
import {buildAgencyDocumentHeaderHtml,getDocumentBrandingPrintCSS,getDocumentIdentityLocaleLayout} from "./documentBranding";

describe("locale-aware document identity",()=>{
  test.each([["ar","right"],["fr","left"],["en","left"]])("%s anchors the complete group physically %s with the default logo-edge order",(lang,side)=>{const layout=getDocumentIdentityLocaleLayout({headerPlacement:"inline-start"},lang),html=buildAgencyDocumentHeaderHtml({agency:{nameAr:"وكالة",agencyNameLatin:"Agency",logoUrl:"logo.png"},config:{headerPlacement:"inline-start"},lang});expect(layout).toMatchObject({side,logoAtEdge:true});expect(html).toContain(`identity-side-${side}`);expect(html).toContain("identity-order-logo-edge");});
  test("explicit reverse order remains available without changing locale anchoring",()=>{expect(getDocumentIdentityLocaleLayout({headerPlacement:"inline-end"},"ar")).toMatchObject({side:"right",logoAtEdge:false});expect(getDocumentIdentityLocaleLayout({headerPlacement:"inline-end"},"fr")).toMatchObject({side:"left",logoAtEdge:false});});
  test.each(["minimal","modern","formal"])("%s print CSS separates physical side from internal order",(style)=>{const css=getDocumentBrandingPrintCSS({style});expect(css).toContain(".identity-side-right .document-branding-header{justify-content:flex-end;text-align:right}");expect(css).toContain(".identity-side-left .document-branding-header{justify-content:flex-start;text-align:left}");expect(css).toContain(".identity-order-logo-edge.identity-dir-rtl:not(.header-placement-stacked) .document-branding-logo{order:2}");expect(css).toContain(".identity-order-logo-edge.identity-dir-ltr:not(.header-placement-stacked) .document-branding-logo{order:0}");});
});

describe("locale identity preview switching",()=>{let host,root;beforeEach(()=>{global.IS_REACT_ACT_ENVIRONMENT=true;host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);});afterEach(async()=>{await act(async()=>root.unmount());host.remove();delete global.IS_REACT_ACT_ENVIRONMENT;});
  test("AR FR AR EN moves the group side and preserves logo/name sizes",async()=>{const agency={nameAr:"وكالة",agencyNameLatin:"Agency",logoUrl:"logo.png"},config={headerPlacement:"inline-start",headerLogoSize:31,headerNameSize:24};for(const [lang,side,name] of [["ar","right","وكالة"],["fr","left","Agency"],["ar","right","وكالة"],["en","left","Agency"]]){await act(async()=>root.render(<AgencyDocumentBranding agency={agency} config={config} t={TRANSLATIONS[lang]} lang={lang} dir={lang==='ar'?'rtl':'ltr'}/>));const shell=host.querySelector("header.document-branding"),paper=host.querySelector("[data-preview-paper]");expect(shell.classList.contains(`identity-side-${side}`)).toBe(true);expect(shell.classList.contains("identity-order-logo-edge")).toBe(true);expect(shell.querySelector(".document-branding-agency-names").textContent).toBe(name);expect(paper.style.getPropertyValue("--branding-logo-size")).toBe("31mm");expect(paper.style.getPropertyValue("--branding-name-size")).toBe("24pt");}});
});
